services:
  portfolio:
    image: ghcr.io/theo-stoffelbach/portefolio:latest
    container_name: portfolio
    restart: unless-stopped
    
    # Label pour Watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    
    expose:
      - "3000"
    env_file:
      - .env.runtime
    environment:
      NODE_ENV: production
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - webnet
      - npm-public
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  webnet:
    external: true
  npm-public:
    external: true
